version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggin ECR 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 711293602624.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - cd ../..
      - ls
      - cd ./application
      - echo Starting Build at 'date'
      - echo Building Docker Images...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Completed build at 'date'
      - echo Pushomg the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG