---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    name: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      service: python-application
  template:
    metadata:
      labels:
        service: python-application
    spec:
      containers:
      - name: python-application
        image: 
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always
