---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    name: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      service: python-application
  template:
    metadata:
      labels:
        service: python-application
    spec:
      containers:
      - name: python-application
        image: 515446315775.dkr.ecr.us-east-1.amazonaws.com/application:latest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
