apiVersion: v1
kind: Service
metadata:
  name: python-application
spec:
  selector:
    app.kubernetes.io/name: python-application
  ports:
  - name: "5151"
    protocol: TCP
    port: 5151
    targetPort: 5151